"""Add published bool to Product - for real

Revision ID: 12f9f919875
Revises: 297bd8850f5
Create Date: 2015-08-02 20:39:59.609085

"""

# revision identifiers, used by Alembic.
revision = '12f9f919875'
down_revision = '297bd8850f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('published', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'published')
    ### end Alembic commands ###
