"""empty message

Revision ID: 1902ec4cf88
Revises: 1de3ecf7aac
Create Date: 2015-08-16 21:06:16.356902

"""

# revision identifiers, used by Alembic.
revision = '1902ec4cf88'
down_revision = '1de3ecf7aac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('product_images', 'path')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('path', sa.VARCHAR(length=64), nullable=True))
    ### end Alembic commands ###
