"""empty message

Revision ID: 1de3ecf7aac
Revises: 29ad2fc7c1c
Create Date: 2015-08-06 01:03:10.320519

"""

# revision identifiers, used by Alembic.
revision = '1de3ecf7aac'
down_revision = '29ad2fc7c1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('filename', sa.String(length=64), nullable=True))
    #op.drop_column('product_images', 'path')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('product_images', sa.Column('path', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('product_images', 'filename')
    ### end Alembic commands ###
