"""Add published bool to Product

Revision ID: 297bd8850f5
Revises: 5185a7d692f
Create Date: 2015-08-02 20:29:29.245063

"""

# revision identifiers, used by Alembic.
revision = '297bd8850f5'
down_revision = '5185a7d692f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
