"""Gallery img bool

Revision ID: 36f8d7273ab
Revises: 12f9f919875
Create Date: 2015-08-03 11:06:06.213112

"""

# revision identifiers, used by Alembic.
revision = '36f8d7273ab'
down_revision = '12f9f919875'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('gallery_image', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'gallery_image')
    ### end Alembic commands ###
