"""product options

Revision ID: 3ca84356c8c
Revises: 2134c2b654
Create Date: 2015-08-22 09:26:21.762707

"""

# revision identifiers, used by Alembic.
revision = '3ca84356c8c'
down_revision = '2134c2b654'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('product_images', 'path')
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('product_images', sa.Column('path', sa.VARCHAR(length=128), nullable=True))
    ### end Alembic commands ###
    pass
