"""empty message

Revision ID: 5185a7d692f
Revises: 4113c17144
Create Date: 2015-07-27 21:43:07.366541

"""

# revision identifiers, used by Alembic.
revision = '5185a7d692f'
down_revision = '4113c17144'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('creation_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'creation_date')
    ### end Alembic commands ###
